version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    env_file:
      - .env
  web:
    build: .
    command: sh ./docker-web-command.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=db

